---
- name: Install packages requirements for openstack-ansible
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: true
    cache_valid_time: 3600
    install-recommends: false
  register: apt_res
  retries: 0
  delay: 3
  until: apt_res is success
  loop: "{{ required_packages | default([]) }}"
