- name: configure network
  ansible.builtin.include_tasks: netplan.yml

- name: Gather network facts
  ansible.builtin.setup:
    gather_subset:
      - network

- name: configure ssh
  ansible.builtin.include_tasks: ssh.yml

- name: add environment file
  become: true
  ansible.builtin.template:
    src: environment.j2
    dest: /etc/environment
