- name: Create .ssh directory for root user
  become: true
  ansible.builtin.file:
    path: /root/.ssh/
    state: directory

- name: Generate an OpenSSH keypair on os0
  become: true
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_rsa
  register: result
  delegate_to: "os0"
  run_once: true

- name: Create authorized_keys file
  become: true
  ansible.builtin.file:
    path: /root/.ssh/authorized_keys
    state: touch

- name: Add public key to authorized_keys
  become: true
  ansible.builtin.blockinfile:
    path: /root/.ssh/authorized_keys
    block: "{{ result.public_key }}"
