- name: Create .ssh directory for root user
  become: true
  ansible.builtin.file:
    path: /root/.ssh/
    state: directory

- name: Copy private key for root user
  become: true
  ansible.builtin.copy:
    src: insecure_vagrant_private_key
    dest: /root/.ssh/id_cluster
    mode: '0600'

- name: Copy vagrat authorized_keys for root user
  become: true
  ansible.builtin.copy:
    src: /home/vagrant/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: '0600'
    remote_src: true

- name: Copy ssh config for root user
  become: true
  ansible.builtin.template:
    src: "ssh_config.yml.j2"
    dest: /root/.ssh/config
